plugins:
  - jest
  - babel
env:
  node: true
  jest: true
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0